/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        xs: '375px',
      },
      colors: {
        tg: {
          bg: 'var(--tg-theme-bg-color)',
          text: 'var(--tg-theme-text-color)',
          hint: 'var(--tg-theme-hint-color)',
          link: 'var(--tg-theme-link-color)',
          button: 'var(--tg-theme-button-color)',
          'button-text': 'var(--tg-theme-button-text-color)',
          'secondary-bg': 'var(--tg-theme-secondary-bg-color)',
        },
        dnd: {
          ink: 'var(--dnd-ink)',
          bg: 'var(--dnd-bg)',
          surface: 'var(--dnd-surface)',
          'surface-raised': 'var(--dnd-surface-raised)',
          'surface-lifted': 'var(--dnd-surface-lifted)',
          'surface-elevated': 'var(--dnd-surface-raised)', // alias legacy
          border: 'var(--dnd-border)',
          'border-strong': 'var(--dnd-border-strong)',
          gold: 'var(--dnd-gold)',
          'gold-bright': 'var(--dnd-gold-bright)',
          'gold-dim': 'var(--dnd-gold-dim)',
          'gold-deep': 'var(--dnd-gold-deep)',
          parchment: 'var(--dnd-parchment)',
          text: 'var(--dnd-text)',
          'text-muted': 'var(--dnd-text-muted)',
          'text-faint': 'var(--dnd-text-faint)',
          'text-secondary': 'var(--dnd-text-muted)', // alias legacy
          danger: 'var(--dnd-crimson)',
          crimson: 'var(--dnd-crimson)',
          'crimson-bright': 'var(--dnd-crimson-bright)',
          'crimson-deep': 'var(--dnd-crimson-deep)',
          success: 'var(--dnd-emerald)',
          emerald: 'var(--dnd-emerald)',
          'emerald-bright': 'var(--dnd-emerald-bright)',
          'emerald-deep': 'var(--dnd-emerald-deep)',
          arcane: 'var(--dnd-arcane)',
          'arcane-bright': 'var(--dnd-arcane-bright)',
          'arcane-deep': 'var(--dnd-arcane-deep)',
          info: 'var(--dnd-cobalt)',
          cobalt: 'var(--dnd-cobalt)',
          'cobalt-bright': 'var(--dnd-cobalt-bright)',
          amber: 'var(--dnd-amber)',
          highlight: 'var(--dnd-amber)',
          'highlight-muted': 'var(--dnd-amber)',
          'success-text': 'var(--dnd-emerald-bright)',
          'arcane-text': 'var(--dnd-arcane-bright)',
          'info-text': 'var(--dnd-cobalt-bright)',
          'chip-bg': 'var(--dnd-chip-bg)',
          'chip-border': 'var(--dnd-chip-border)',
          overlay: 'var(--dnd-overlay)',
        },
      },
      fontFamily: {
        cinzel: ['Cinzel', 'Georgia', 'serif'],
        display: ['"Cormorant Unicase"', 'Cinzel', 'Georgia', 'serif'],
        body: ['Fraunces', 'Georgia', 'serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        'dnd-glow': '0 0 20px var(--dnd-gold-glow)',
        'parchment-sm': 'var(--shadow-1)',
        'parchment-md': 'var(--shadow-2)',
        'parchment-lg': 'var(--shadow-3)',
        'parchment-xl': 'var(--shadow-4)',
        'parchment-2xl': 'var(--shadow-5)',
        'illumination': 'var(--halo-gold)',
        'halo-gold': 'var(--halo-gold)',
        'halo-arcane': 'var(--halo-arcane)',
        'halo-danger': 'var(--halo-danger)',
        engrave: 'var(--shadow-engrave)',
      },
      backgroundImage: {
        'gradient-parchment': 'var(--gradient-parchment)',
        'gradient-gold': 'var(--gradient-gold)',
        'gradient-hero-halo': 'var(--gradient-hero-halo)',
        'gradient-arcane-mist': 'var(--gradient-arcane-mist)',
        'gradient-ember': 'var(--gradient-ember)',
        'gradient-flourish': 'var(--gradient-flourish)',
        'grain-overlay': 'var(--grain-overlay)',
      },
      transitionTimingFunction: {
        'ease-parchment': 'cubic-bezier(0.22, 1, 0.36, 1)',
        'ease-ink': 'cubic-bezier(0.22, 0.61, 0.36, 1)',
      },
      keyframes: {
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '20%': { transform: 'translateX(-4px)' },
          '40%': { transform: 'translateX(4px)' },
          '60%': { transform: 'translateX(-2px)' },
          '80%': { transform: 'translateX(2px)' },
        },
        bob: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
        'ink-spread': {
          '0%': { transform: 'scale(0)', opacity: '0.4' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
        'sigil-rotate': {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
      },
      animation: {
        shake: 'shake 250ms ease-out',
        bob: 'bob 1.8s ease-in-out infinite',
        'ink-spread': 'ink-spread 320ms ease-out forwards',
        'sigil-rotate': 'sigil-rotate 5s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
